# Generated by Django 3.2.13 on 2022-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(default='male', max_length=255, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=255, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='male', max_length=255, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=255, verbose_name='Gender'),
        ),
    ]
